# Numpy 

* NumPy is a Python library.

* NumPy is used for working with arrays.

* NumPy is short for "Numerical Python".

In [2]:
import numpy as np

In [30]:
np1 = np.array([1,2,3,'s1','s2', 2+2, 3*2, {'name': 'arc'}])

In [31]:
np1

array([1, 2, 3, 's1', 's2', 4, 6, {'name': 'arc'}], dtype=object)

In [32]:
type(np1)

numpy.ndarray

In [33]:
np2 = np.array(list(range(1,50,)))

In [34]:
np2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [35]:
print(np.min(np2))

1


In [37]:
l1 = list(range(10,100,5))

l1

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

In [38]:
np.min(l1)

10

In [39]:
np2 = np.array([ [0,1,2], [2,4,5] ])

In [40]:
print(np2)

[[0 1 2]
 [2 4 5]]


In [25]:
print(l1)
print()
print(np1)
print()
print(np2)

[10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]

[1 2 3 's1s2' 4 6 {'name': 'arc'}]

[[0 1 2]
 [2 4 5]]


In [43]:
print(f'np1.shape() = {np1.shape}')

print(f'np2.shape() = {np2.shape}')

print(f'l1.shape() = {len(l1)}')

np1.shape() = (8,)
np2.shape() = (2, 3)
l1.shape() = 18


In [45]:
print(f'type(np1) = {type(np1)}   , np1. =dtype ={np1.dtype}')

type(np1) = <class 'numpy.ndarray'>   , np1. =dtype =object


In [49]:
print(f'type(np2) = {type(np2)}   , np2.dtype = {np2.dtype}')

type(np2) = <class 'numpy.ndarray'>   , np2.dtype = int32


In [50]:
np2

array([[0, 1, 2],
       [2, 4, 5]])

In [51]:
l2 = [[0,1,2],
      [2,4,5]]

l2

[[0, 1, 2], [2, 4, 5]]

In [52]:
l2[0][1] = 3
l2

[[0, 3, 2], [2, 4, 5]]

In [55]:
np2[0,1] = 3

np2

array([[0, 3, 2],
       [2, 4, 5]])

In [56]:
l2[0][1] = 'text'

l2

[[0, 'text', 2], [2, 4, 5]]

In [58]:
mat2 = np.arange(0,10,3)
mat2

array([0, 3, 6, 9])

In [59]:
mat2 = np.arange(10,100,5)

print(f'mat2 = {mat2}')

npRange = np.array(range(10,100,5))

print(f'npRange = {npRange}')

mat2 = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
npRange = [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [61]:
mat3 = np.linspace(0,10,20)

print(mat3)
print(mat3.shape)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
(20,)


In [63]:
mat4 = np.random.rand(5,5)

print(mat4)

[[0.42999806 0.35984448 0.53949964 0.38214355 0.13141843]
 [0.86463698 0.87000428 0.56045825 0.59435655 0.65667623]
 [0.40703377 0.77288736 0.15687023 0.13133209 0.33092128]
 [0.13828842 0.65908309 0.32136535 0.11378898 0.42035538]
 [0.87347092 0.79001222 0.59388711 0.49366786 0.03870813]]
